---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
  namespace: development
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "9200"
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    io.kompose.service: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
