---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kibana
  name: kibana
  namespace: development
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "5601"
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    io.kompose.service: kibana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
